# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyticsParams.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 157)
        self.strideLengthLabel = QtWidgets.QLabel(Dialog)
        self.strideLengthLabel.setGeometry(QtCore.QRect(30, 50, 121, 16))
        self.strideLengthLabel.setObjectName("strideLengthLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 391, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.strideTimeLabel = QtWidgets.QLabel(Dialog)
        self.strideTimeLabel.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.strideTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.strideTimeLabel.setObjectName("strideTimeLabel")
        self.gaitSpeedLabel = QtWidgets.QLabel(Dialog)
        self.gaitSpeedLabel.setGeometry(QtCore.QRect(30, 90, 121, 16))
        self.gaitSpeedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gaitSpeedLabel.setObjectName("gaitSpeedLabel")
        self.strideWidthLabel = QtWidgets.QLabel(Dialog)
        self.strideWidthLabel.setGeometry(QtCore.QRect(30, 110, 121, 16))
        self.strideWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.strideWidthLabel.setObjectName("strideWidthLabel")
        self.strideLengthValue = QtWidgets.QLabel(Dialog)
        self.strideLengthValue.setGeometry(QtCore.QRect(160, 50, 201, 16))
        self.strideLengthValue.setObjectName("strideLengthValue")
        self.strideTimeValue = QtWidgets.QLabel(Dialog)
        self.strideTimeValue.setGeometry(QtCore.QRect(160, 70, 201, 16))
        self.strideTimeValue.setObjectName("strideTimeValue")
        self.gaitSpeedValue = QtWidgets.QLabel(Dialog)
        self.gaitSpeedValue.setGeometry(QtCore.QRect(160, 90, 201, 16))
        self.gaitSpeedValue.setObjectName("gaitSpeedValue")
        self.strideWidthValue = QtWidgets.QLabel(Dialog)
        self.strideWidthValue.setGeometry(QtCore.QRect(160, 110, 201, 16))
        self.strideWidthValue.setObjectName("strideWidthValue")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.strideLengthLabel.setText(_translate("Dialog", "Stride Length (cm):"))
        self.label_2.setText(_translate("Dialog", "Spatio-temporal Parameters"))
        self.strideTimeLabel.setText(_translate("Dialog", "Stride Time (s):"))
        self.gaitSpeedLabel.setText(_translate("Dialog", "Gait Speed (m/s):"))
        self.strideWidthLabel.setText(_translate("Dialog", "Stride Width (cm):"))
        self.strideLengthValue.setText(_translate("Dialog", "-"))
        self.strideTimeValue.setText(_translate("Dialog", "-"))
        self.gaitSpeedValue.setText(_translate("Dialog", "-"))
        self.strideWidthValue.setText(_translate("Dialog", "-"))
