# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comparativeStats.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 128)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.aveDTWLabel = QtWidgets.QLabel(Dialog)
        self.aveDTWLabel.setGeometry(QtCore.QRect(20, 40, 181, 16))
        self.aveDTWLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aveDTWLabel.setObjectName("aveDTWLabel")
        self.aveCorrLabel = QtWidgets.QLabel(Dialog)
        self.aveCorrLabel.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.aveCorrLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aveCorrLabel.setObjectName("aveCorrLabel")
        self.avePearCorrLabel = QtWidgets.QLabel(Dialog)
        self.avePearCorrLabel.setGeometry(QtCore.QRect(20, 80, 181, 21))
        self.avePearCorrLabel.setObjectName("avePearCorrLabel")
        self.aveDTWValue = QtWidgets.QLabel(Dialog)
        self.aveDTWValue.setGeometry(QtCore.QRect(210, 40, 171, 21))
        self.aveDTWValue.setObjectName("aveDTWValue")
        self.aveCorrValue = QtWidgets.QLabel(Dialog)
        self.aveCorrValue.setGeometry(QtCore.QRect(210, 60, 171, 21))
        self.aveCorrValue.setObjectName("aveCorrValue")
        self.avePearCorrValue = QtWidgets.QLabel(Dialog)
        self.avePearCorrValue.setGeometry(QtCore.QRect(210, 80, 171, 21))
        self.avePearCorrValue.setObjectName("avePearCorrValue")
        self.avePValuesLabel = QtWidgets.QLabel(Dialog)
        self.avePValuesLabel.setGeometry(QtCore.QRect(20, 100, 181, 21))
        self.avePValuesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avePValuesLabel.setObjectName("avePValuesLabel")
        self.avePValuesValue = QtWidgets.QLabel(Dialog)
        self.avePValuesValue.setGeometry(QtCore.QRect(210, 100, 171, 21))
        self.avePValuesValue.setObjectName("avePValuesValue")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Angles Analysis"))
        self.aveDTWLabel.setText(_translate("Dialog", "Average DTW:"))
        self.aveCorrLabel.setText(_translate("Dialog", "Average Correlation:"))
        self.avePearCorrLabel.setText(_translate("Dialog", "Average Pearson Correlation:"))
        self.aveDTWValue.setText(_translate("Dialog", "-"))
        self.aveCorrValue.setText(_translate("Dialog", "-"))
        self.avePearCorrValue.setText(_translate("Dialog", "-"))
        self.avePValuesLabel.setText(_translate("Dialog", "Average P-Values:"))
        self.avePValuesValue.setText(_translate("Dialog", "-"))
