# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comparativeParams.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 128)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.avgDTWLabel = QtWidgets.QLabel(Dialog)
        self.avgDTWLabel.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.avgDTWLabel.setObjectName("avgDTWLabel")
        self.avgCorrLabel = QtWidgets.QLabel(Dialog)
        self.avgCorrLabel.setGeometry(QtCore.QRect(20, 60, 131, 16))
        self.avgCorrLabel.setObjectName("avgCorrLabel")
        self.avgPearCorrLabel = QtWidgets.QLabel(Dialog)
        self.avgPearCorrLabel.setGeometry(QtCore.QRect(20, 80, 181, 21))
        self.avgPearCorrLabel.setObjectName("avgPearCorrLabel")
        self.avgDTWValue = QtWidgets.QLabel(Dialog)
        self.avgDTWValue.setGeometry(QtCore.QRect(210, 40, 171, 21))
        self.avgDTWValue.setObjectName("avgDTWValue")
        self.avgCorrValue = QtWidgets.QLabel(Dialog)
        self.avgCorrValue.setGeometry(QtCore.QRect(210, 60, 171, 21))
        self.avgCorrValue.setObjectName("avgCorrValue")
        self.avgPearCorrValue = QtWidgets.QLabel(Dialog)
        self.avgPearCorrValue.setGeometry(QtCore.QRect(210, 80, 171, 21))
        self.avgPearCorrValue.setObjectName("avgPearCorrValue")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Angles Analysis"))
        self.avgDTWLabel.setText(_translate("Dialog", "Average DTW:"))
        self.avgCorrLabel.setText(_translate("Dialog", "Average Correlation:"))
        self.avgPearCorrLabel.setText(_translate("Dialog", "Average Pearson Correlation:"))
        self.avgDTWValue.setText(_translate("Dialog", "-"))
        self.avgCorrValue.setText(_translate("Dialog", "-"))
        self.avgPearCorrValue.setText(_translate("Dialog", "-"))
