# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poseConfiguration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 256)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 20, 181, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.poseEstimationPage = QtWidgets.QStackedWidget(Dialog)
        self.poseEstimationPage.setGeometry(QtCore.QRect(10, 90, 381, 101))
        self.poseEstimationPage.setObjectName("poseEstimationPage")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.openPosePathButton = QtWidgets.QPushButton(self.page)
        self.openPosePathButton.setGeometry(QtCore.QRect(10, 10, 131, 32))
        self.openPosePathButton.setObjectName("openPosePathButton")
        self.openPosePathLabel = QtWidgets.QLabel(self.page)
        self.openPosePathLabel.setGeometry(QtCore.QRect(150, 10, 211, 31))
        self.openPosePathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.openPosePathLabel.setObjectName("openPosePathLabel")
        self.modelPathButton = QtWidgets.QPushButton(self.page)
        self.modelPathButton.setGeometry(QtCore.QRect(10, 60, 131, 32))
        self.modelPathButton.setObjectName("modelPathButton")
        self.modelPathLabel = QtWidgets.QLabel(self.page)
        self.modelPathLabel.setGeometry(QtCore.QRect(150, 60, 211, 31))
        self.modelPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modelPathLabel.setObjectName("modelPathLabel")
        self.poseEstimationPage.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(120, 40, 151, 16))
        self.label_4.setObjectName("label_4")
        self.poseEstimationPage.addWidget(self.page_2)
        self.openPoseButton = QtWidgets.QRadioButton(Dialog)
        self.openPoseButton.setGeometry(QtCore.QRect(100, 50, 100, 20))
        self.openPoseButton.setChecked(True)
        self.openPoseButton.setObjectName("openPoseButton")
        self.rtmPoseButton = QtWidgets.QRadioButton(Dialog)
        self.rtmPoseButton.setGeometry(QtCore.QRect(200, 50, 100, 20))
        self.rtmPoseButton.setChecked(False)
        self.rtmPoseButton.setObjectName("rtmPoseButton")

        self.retranslateUi(Dialog)
        self.poseEstimationPage.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Pose Estimation Model"))
        self.openPosePathButton.setText(_translate("Dialog", "OpenPose Path"))
        self.openPosePathLabel.setText(_translate("Dialog", "Please set path"))
        self.modelPathButton.setText(_translate("Dialog", "Model Path"))
        self.modelPathLabel.setText(_translate("Dialog", "Please set path"))
        self.label_4.setText(_translate("Dialog", "RTMPose Configuration"))
        self.openPoseButton.setText(_translate("Dialog", "OpenPose"))
        self.rtmPoseButton.setText(_translate("Dialog", "RTMPose"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
