# Form implementation generated from reading ui file 'NEWthesis.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow
import resources  # Import the generated resource file for images and icons (PyQt6 resource)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 867)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.icon_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_widget.setGeometry(QtCore.QRect(10, 0, 281, 929))
        self.icon_widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.icon_widget.setStyleSheet("")
        self.icon_widget.setObjectName("icon_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.icon_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resources/directions_walk_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.home_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.home_button.setAutoFillBackground(False)
        self.home_button.setStyleSheet("QPushButton {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        color: black;\n"
"text-align: left;\n"
"    padding-left: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #87CEEB; /* Optional: Light sky blue hover effect */\n"
"    }\n"
"    font: 75 8pt \"Microsoft JhengHei UI\";")
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/home_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(40, 40))
        self.home_button.setCheckable(True)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        spacerItem1 = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.cameras_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.cameras_button.setAutoFillBackground(False)
        self.cameras_button.setStyleSheet("QPushButton {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        color: black;\n"
"text-align: left;\n"
"    padding-left: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #87CEEB; /* Optional: Light sky blue hover effect */\n"
"    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/photo_camera_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cameras_button.setIcon(icon1)
        self.cameras_button.setIconSize(QtCore.QSize(40, 40))
        self.cameras_button.setCheckable(True)
        self.cameras_button.setObjectName("cameras_button")
        self.verticalLayout.addWidget(self.cameras_button)
        spacerItem2 = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.dataviewer_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.dataviewer_button.setAutoFillBackground(False)
        self.dataviewer_button.setStyleSheet("QPushButton {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        color: black;\n"
"text-align: left;\n"
"    padding-left: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #87CEEB; /* Optional: Light sky blue hover effect */\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/storage_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dataviewer_button.setIcon(icon2)
        self.dataviewer_button.setIconSize(QtCore.QSize(40, 40))
        self.dataviewer_button.setCheckable(True)
        self.dataviewer_button.setObjectName("dataviewer_button")
        self.verticalLayout.addWidget(self.dataviewer_button)
        spacerItem3 = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        # Exit button at the bottom
        self.exit_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.exit_button.setAutoFillBackground(False)
        self.exit_button.setStyleSheet("QPushButton {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        color: black;\n"
"text-align: left;\n"
"    padding-left: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #87CEEB; /* Optional: Light sky blue hover effect */\n"
"    }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/logout_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_button.setIcon(icon3)
        self.exit_button.setIconSize(QtCore.QSize(40, 40))
        self.exit_button.setCheckable(True)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)

        self.label_7 = QtWidgets.QLabel(parent=self.icon_widget)
        self.label_7.setStyleSheet("font: 150 12pt \"Microsoft YaHei UI\";\n"
"\n"
"color: #f0f0f0;\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.frame_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.frame_widget.setGeometry(QtCore.QRect(290, 0, 941, 121))
        self.frame_widget.setStyleSheet("")
        self.frame_widget.setObjectName("frame_widget")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 93, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        color: white;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #87CEEB; /* Optional: Light sky blue hover effect */\n"
"    }\n"
"    font: 75 8pt \"Microsoft JhengHei UI\";")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../THESIS(4)/resources/menu_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_widget)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 611, 71))
        self.label_2.setStyleSheet("font: 75 26pt \"Microsoft JhengHei UI\";\n"
"color: black;")
        self.label_2.setObjectName("label_2")
        self.main_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(290, 120, 941, 771))
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 911, 711))
        self.stackedWidget.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;  /* Adjust the text color as needed */\n"
"    padding: 0;    /* Remove any padding if necessary */\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_group = QtWidgets.QFrame(parent=self.home_page)
        self.frame_group.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_group.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_group.setObjectName("frame_group")
        self.verticalLayout_2.addWidget(self.frame_group)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.home_page)
        self.pushButton_2.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.home_page)
        self.pushButton_3.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.home_page)
        self.pushButton_13.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.home_page)
        self.pushButton_4.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.stackedWidget.addWidget(self.home_page)
        self.cameras_page = QtWidgets.QWidget()
        self.cameras_page.setObjectName("cameras_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.cameras_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 40, 201, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startmcrec = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.startmcrec.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.startmcrec.setObjectName("startmcrec")
        self.verticalLayout_3.addWidget(self.startmcrec)
        self.stoprec = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.stoprec.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.stoprec.setObjectName("stoprec")
        self.verticalLayout_3.addWidget(self.stoprec)
        self.detectavailcam = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.detectavailcam.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.detectavailcam.setObjectName("detectavailcam")
        self.verticalLayout_3.addWidget(self.detectavailcam)
        self.startcrec = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.startcrec.setStyleSheet(" QPushButton {\n"
"        background-color: #FFFFFF;  /* Darker shade */\n"
"        color: black\n"
";  /* Text color */\n"
"     \n"
"    }")
        self.startcrec.setObjectName("startcrec")
        self.verticalLayout_3.addWidget(self.startcrec)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.cameras_page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 320, 221, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.autoprocess = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.autoprocess.setStyleSheet("")
        self.autoprocess.setObjectName("autoprocess")
        self.verticalLayout_4.addWidget(self.autoprocess)
        self.genntbk = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.genntbk.setStyleSheet("")
        self.genntbk.setObjectName("genntbk")
        self.verticalLayout_4.addWidget(self.genntbk)
        self.autoopenblender = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.autoopenblender.setStyleSheet("")
        self.autoopenblender.setObjectName("autoopenblender")
        self.verticalLayout_4.addWidget(self.autoopenblender)
        self.dispcharoverlay = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.dispcharoverlay.setStyleSheet("")
        self.dispcharoverlay.setObjectName("dispcharoverlay")
        self.verticalLayout_4.addWidget(self.dispcharoverlay)
        self.CharucoSquareSize = QtWidgets.QSpinBox(parent=self.cameras_page)
        self.CharucoSquareSize.setGeometry(QtCore.QRect(240, 530, 61, 20))
        self.CharucoSquareSize.setStyleSheet("")
        self.CharucoSquareSize.setObjectName("CharucoSquareSize")
        self.CharucoSquareSize_2 = QtWidgets.QLabel(parent=self.cameras_page)
        self.CharucoSquareSize_2.setGeometry(QtCore.QRect(70, 530, 161, 16))
        self.CharucoSquareSize_2.setStyleSheet("")
        self.CharucoSquareSize_2.setObjectName("CharucoSquareSize_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.cameras_page)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(70, 570, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.recname = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.recname.setStyleSheet("")
        self.recname.setObjectName("recname")
        self.verticalLayout_5.addWidget(self.recname)
        self.tag = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.tag.setStyleSheet("")
        self.tag.setObjectName("tag")
        self.verticalLayout_5.addWidget(self.tag)
        self.fullpath = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.fullpath.setStyleSheet("")
        self.fullpath.setObjectName("fullpath")
        self.verticalLayout_5.addWidget(self.fullpath)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.cameras_page)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(240, 570, 541, 82))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;  /* Adjust the text color as needed */\n"
"    padding: 0;    /* Remove any padding if necessary */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_6.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;  /* Adjust the text color as needed */\n"
"    padding: 0;    /* Remove any padding if necessary */\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;  /* Adjust the text color as needed */\n"
"    padding: 0;    /* Remove any padding if necessary */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.stackedWidget.addWidget(self.cameras_page)
        self.dataviewer_page = QtWidgets.QWidget()
        self.dataviewer_page.setObjectName("dataviewer_page")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.dataviewer_page)
        self.pushButton_9.setGeometry(QtCore.QRect(420, 610, 71, 28))
        self.pushButton_9.setStyleSheet(" QPushButton {\n"
"        background-color: white;/* Darker shade */\n"
"        color: white;  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/pause_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.dataviewer_page)
        self.pushButton_10.setGeometry(QtCore.QRect(80, 610, 71, 28))
        self.pushButton_10.setStyleSheet(" QPushButton {\n"
"        background-color: white; /* Darker shade */\n"
"        color: white;  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_10.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/skip_previous_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.dataviewer_page)
        self.pushButton_11.setGeometry(QtCore.QRect(740, 610, 71, 28))
        self.pushButton_11.setStyleSheet(" QPushButton {\n"
"        background-color: white;  /* Darker shade */\n"
"        color: white;  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_11.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/skip_next_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.progressbar = QtWidgets.QSlider(parent=self.dataviewer_page)
        self.progressbar.setGeometry(QtCore.QRect(80, 570, 731, 22))
        self.progressbar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressbar.setObjectName("progressbar")
        self.graph = QtWidgets.QWidget(parent=self.dataviewer_page)
        self.graph.setGeometry(QtCore.QRect(80, 70, 731, 491))
        self.graph.setObjectName("graph")
        self.label_8 = QtWidgets.QLabel(parent=self.dataviewer_page)
        self.label_8.setGeometry(QtCore.QRect(80, 660, 141, 16))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.dataviewer_page)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 660, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.stackedWidget.addWidget(self.dataviewer_page)
        self.directoryviewer_page = QtWidgets.QWidget()
        self.directoryviewer_page.setObjectName("directoryviewer_page")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.directoryviewer_page)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 450, 199, 28))
        self.pushButton_12.setStyleSheet(" QPushButton {\n"
"        background-color: #688DA4;  /* Darker shade */\n"
"        color: white;  /* Text color */\n"
"     \n"
"    }")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_9 = QtWidgets.QLabel(parent=self.directoryviewer_page)
        self.label_9.setGeometry(QtCore.QRect(30, 500, 141, 16))
        self.label_9.setStyleSheet("color: white\n"
"")
        self.label_9.setObjectName("label_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.directoryviewer_page)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 40, 891, 391))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.directoryviewer_page)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 500, 601, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.stackedWidget.addWidget(self.directoryviewer_page)
        self.activerecording_page = QtWidgets.QWidget()
        self.activerecording_page.setObjectName("activerecording_page")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.activerecording_page)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 881, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.stackedWidget.addWidget(self.activerecording_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.pushButton.toggled['bool'].connect(self.icon_widget.setHidden) # type: ignore
        self.exit_button.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.cameras_button.setText(_translate("MainWindow", "Cameras"))
        self.dataviewer_button.setText(_translate("MainWindow", "Data Viewer"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.label_7.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "Markerless Gait Analysis"))
        self.pushButton_2.setText(_translate("MainWindow", "New Recording"))
        self.pushButton_3.setText(_translate("MainWindow", "Load Recording"))
        self.pushButton_13.setText(_translate("MainWindow", "Process"))
        self.pushButton_4.setText(_translate("MainWindow", "Import Videos"))
        self.startmcrec.setText(_translate("MainWindow", "Start Motion Capture Recording"))
        self.stoprec.setText(_translate("MainWindow", "Stop Recording"))
        self.detectavailcam.setText(_translate("MainWindow", "Detect Available Cameras"))
        self.startcrec.setText(_translate("MainWindow", "Start Calibration Recording"))
        self.autoprocess.setText(_translate("MainWindow", "Auto Process Videos on Save"))
        self.genntbk.setText(_translate("MainWindow", "Generate Jupyter Notebook"))
        self.autoopenblender.setText(_translate("MainWindow", "Auto Open in Blender"))
        self.dispcharoverlay.setText(_translate("MainWindow", "Display Charuco Overlay"))
        self.CharucoSquareSize.setToolTip(_translate("MainWindow", "<html><head/><body><p>Charuco Square Size (mm)</p></body></html>"))
        self.CharucoSquareSize.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Charuco Square Size (mm)</p><p><br/></p></body></html>"))
        self.CharucoSquareSize_2.setText(_translate("MainWindow", "Charuco Square Size (mm):"))
        self.recname.setText(_translate("MainWindow", "Recording Name:"))
        self.tag.setText(_translate("MainWindow", "Tag (Optional):"))
        self.fullpath.setText(_translate("MainWindow", "Full Path:"))
        self.label_8.setText(_translate("MainWindow", "Frame Number:"))
        self.pushButton_12.setText(_translate("MainWindow", "Show FreeMoCap Data Folder"))
        self.label_9.setText(_translate("MainWindow", "Session Path:"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Directory"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recording Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))

# Merge the MySideBar class into the main application
class MySideBar(QMainWindow):
    def __init__(self):
        super().__init__()

        # Create an instance of the UI class
        self.ui = Ui_MainWindow()

        # Setup the UI with the QMainWindow as the parent
        self.ui.setupUi(self)

        self.setWindowTitle("SideBar Menu")

        # CONNECT BUTTONS TO SWITCH TO DIFFERENT PAGES
        self.ui.home_button.clicked.connect(self.switch_to_home_page)
        self.ui.cameras_button.clicked.connect(self.switch_to_cameras_page)
        self.ui.dataviewer_button.clicked.connect(self.switch_to_dataviewer_page)

        # TOGGLE NAVIGATION PANE (hide when a button is clicked)
        self.ui.pushButton.toggled.connect(self.toggle_nav_pane)

    def toggle_nav_pane(self, checked):
        # Hide or show the icon_widget (navigation pane)
        self.ui.icon_widget.setVisible(not checked)

    def switch_to_home_page(self):
        self.ui.stackedWidget.setCurrentIndex(0)

    def switch_to_cameras_page(self):
        self.ui.stackedWidget.setCurrentIndex(1)

    def switch_to_dataviewer_page(self):
        self.ui.stackedWidget.setCurrentIndex(2)

if __name__ == "__main__":
    import sys
    app = QApplication([])

    # Set a light theme palette if needed
    app.setStyle("Fusion")
    light_palette = QtGui.QPalette()
    light_palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor(240, 240, 240))  # light grey background
    light_palette.setColor(QtGui.QPalette.ColorRole.WindowText, QtCore.Qt.GlobalColor.black)
    light_palette.setColor(QtGui.QPalette.ColorRole.Base, QtCore.Qt.GlobalColor.white)
    light_palette.setColor(QtGui.QPalette.ColorRole.Button, QtGui.QColor(240, 240, 240))
    app.setPalette(light_palette)

    window = MySideBar()
    window.show()
    sys.exit(app.exec())
