# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_trial_form(object):
    def setupUi(self, trial_form):
        trial_form.setObjectName("trial_form")
        trial_form.resize(400, 105)
        self.buttonBox = QtWidgets.QDialogButtonBox(trial_form)
        self.buttonBox.setGeometry(QtCore.QRect(30, 60, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.trialNameLabel = QtWidgets.QLabel(trial_form)
        self.trialNameLabel.setGeometry(QtCore.QRect(30, 30, 71, 21))
        self.trialNameLabel.setObjectName("trialNameLabel")
        self.trialNameField = QtWidgets.QLineEdit(trial_form)
        self.trialNameField.setGeometry(QtCore.QRect(110, 30, 261, 21))
        self.trialNameField.setObjectName("trialNameField")

        self.retranslateUi(trial_form)
        self.buttonBox.accepted.connect(trial_form.accept) # type: ignore
        self.buttonBox.rejected.connect(trial_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(trial_form)

    def retranslateUi(self, trial_form):
        _translate = QtCore.QCoreApplication.translate
        trial_form.setWindowTitle(_translate("trial_form", "New Trial"))
        self.trialNameLabel.setText(_translate("trial_form", "Trial Name"))
        self.trialNameField.setPlaceholderText(_translate("trial_form", "e.g. Trendelenburg"))
