# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_patient_form(object):
    def setupUi(self, patient_form):
        patient_form.setObjectName("patient_form")
        patient_form.setWindowModality(QtCore.Qt.WindowModal)
        patient_form.resize(400, 246)
        self.buttonBox = QtWidgets.QDialogButtonBox(patient_form)
        self.buttonBox.setGeometry(QtCore.QRect(30, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(patient_form)
        self.label.setGeometry(QtCore.QRect(160, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(patient_form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 361, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("  font: 8pt \"Microsoft JhengHei UI\";\n"
"  text-align: left;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.firstNameField = QtWidgets.QLineEdit(self.layoutWidget)
        self.firstNameField.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    color: #000000; /* Black text */\n"
"    border: 2px solid gray; /* Blue border */\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Change background to light gray when hovered */\n"
"QLineEdit:hover {\n"
"    background-color: #D3D3D3; /* Light gray */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0050A0; /* Darker blue border on focus */\n"
"    background-color: #f0f8ff; /* Light blue background */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}\n"
"\n"
"QLineEdit::selection {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.firstNameField.setText("")
        self.firstNameField.setObjectName("firstNameField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstNameField)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("  font: 8pt \"Microsoft JhengHei UI\";\n"
"  text-align: left;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lastNameField = QtWidgets.QLineEdit(self.layoutWidget)
        self.lastNameField.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    color: #000000; /* Black text */\n"
"    border: 2px solid gray; /* Blue border */\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Change background to light gray when hovered */\n"
"QLineEdit:hover {\n"
"    background-color: #D3D3D3; /* Light gray */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0050A0; /* Darker blue border on focus */\n"
"    background-color: #f0f8ff; /* Light blue background */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}\n"
"\n"
"QLineEdit::selection {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.lastNameField.setText("")
        self.lastNameField.setObjectName("lastNameField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lastNameField)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("  font: 8pt \"Microsoft JhengHei UI\";\n"
"  text-align: left;")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("  font: 8pt \"Microsoft JhengHei UI\";\n"
"  text-align: left;")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.heightField = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.heightField.setStyleSheet("font: 8pt \"Microsoft JhengHei UI\";")
        self.heightField.setObjectName("heightField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heightField)
        self.weightField = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.weightField.setStyleSheet("font: 8pt \"Microsoft YaHei UI\";")
        self.weightField.setObjectName("weightField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weightField)

        self.retranslateUi(patient_form)
        self.buttonBox.accepted.connect(patient_form.accept) # type: ignore
        self.buttonBox.rejected.connect(patient_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(patient_form)

    def retranslateUi(self, patient_form):
        _translate = QtCore.QCoreApplication.translate
        patient_form.setWindowTitle(_translate("patient_form", "Patient Form"))
        self.label.setText(_translate("patient_form", "Patient Details"))
        self.label_2.setText(_translate("patient_form", "First Name"))
        self.label_3.setText(_translate("patient_form", "Last Name"))
        self.label_4.setText(_translate("patient_form", "Height (m)"))
        self.label_5.setText(_translate("patient_form", "Weight (kg)"))
