# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        MainWindow.setStyleSheet("background-color: #FFFCF8")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar_full = QtWidgets.QWidget(self.centralwidget)
        self.sidebar_full.setGeometry(QtCore.QRect(0, 0, 195, 800))
        self.sidebar_full.setMinimumSize(QtCore.QSize(195, 800))
        self.sidebar_full.setMaximumSize(QtCore.QSize(195, 800))
        self.sidebar_full.setAutoFillBackground(False)
        self.sidebar_full.setObjectName("sidebar_full")
        self.sidebar_full_2 = QtWidgets.QWidget(self.sidebar_full)
        self.sidebar_full_2.setEnabled(True)
        self.sidebar_full_2.setGeometry(QtCore.QRect(-30, 0, 230, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_full_2.sizePolicy().hasHeightForWidth())
        self.sidebar_full_2.setSizePolicy(sizePolicy)
        self.sidebar_full_2.setMinimumSize(QtCore.QSize(200, 800))
        self.sidebar_full_2.setMaximumSize(QtCore.QSize(250, 800))
        self.sidebar_full_2.setAutoFillBackground(False)
        self.sidebar_full_2.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    border: 0.4px solid gray; /* Light gray border */\n"
"\n"
"    /* Shadow effect */\n"
"    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\n"
"\n"
"}")
        self.sidebar_full_2.setObjectName("sidebar_full_2")
        self.layoutWidget = QtWidgets.QWidget(self.sidebar_full_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 211, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(21, 0, 21, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Logo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.Logo.setFont(font)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.verticalLayout_3.addWidget(self.Logo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, -1, 7, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainMenu = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(6)
        self.mainMenu.setFont(font)
        self.mainMenu.setStyleSheet("color: #B0B0B0;")
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout.addWidget(self.mainMenu, 0, QtCore.Qt.AlignLeft)
        self.dashboardButton = QtWidgets.QPushButton(self.layoutWidget)
        self.dashboardButton.setMaximumSize(QtCore.QSize(16777213, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dashboardButton.setFont(font)
        self.dashboardButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resourcesnew/Dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboardButton.setIcon(icon)
        self.dashboardButton.setDefault(False)
        self.dashboardButton.setFlat(False)
        self.dashboardButton.setObjectName("dashboardButton")
        self.verticalLayout.addWidget(self.dashboardButton)
        self.camerasButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.camerasButton.setFont(font)
        self.camerasButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resourcesnew/Cameras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camerasButton.setIcon(icon1)
        self.camerasButton.setObjectName("camerasButton")
        self.verticalLayout.addWidget(self.camerasButton)
        self.simulationButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.simulationButton.setFont(font)
        self.simulationButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resourcesnew/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simulationButton.setIcon(icon2)
        self.simulationButton.setObjectName("simulationButton")
        self.verticalLayout.addWidget(self.simulationButton)
        self.jointAnalyticsButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.jointAnalyticsButton.setFont(font)
        self.jointAnalyticsButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resourcesnew/compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jointAnalyticsButton.setIcon(icon3)
        self.jointAnalyticsButton.setObjectName("jointAnalyticsButton")
        self.verticalLayout.addWidget(self.jointAnalyticsButton)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(7, -1, 7, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.directoryMenu = QtWidgets.QLabel(self.layoutWidget)
        self.directoryMenu.setMinimumSize(QtCore.QSize(62, 16))
        self.directoryMenu.setMaximumSize(QtCore.QSize(62, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(6)
        self.directoryMenu.setFont(font)
        self.directoryMenu.setStyleSheet("color: #B0B0B0;")
        self.directoryMenu.setObjectName("directoryMenu")
        self.verticalLayout_2.addWidget(self.directoryMenu)
        self.sessionSelectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sessionSelectButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionSelectButton.sizePolicy().hasHeightForWidth())
        self.sessionSelectButton.setSizePolicy(sizePolicy)
        self.sessionSelectButton.setBaseSize(QtCore.QSize(0, -1))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sessionSelectButton.setFont(font)
        self.sessionSelectButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resourcesnew/Stacks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sessionSelectButton.setIcon(icon4)
        self.sessionSelectButton.setObjectName("sessionSelectButton")
        self.verticalLayout_2.addWidget(self.sessionSelectButton)
        self.sessionSelectedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sessionSelectedLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sessionSelectedLabel.setFont(font)
        self.sessionSelectedLabel.setStyleSheet("QLabel {\n"
"    color: #B0B0B0;\n"
"    font: 6pt \"Microsoft JhengHei UI Light\";\n"
"}")
        self.sessionSelectedLabel.setObjectName("sessionSelectedLabel")
        self.verticalLayout_2.addWidget(self.sessionSelectedLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.participantSelectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.participantSelectButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.participantSelectButton.setFont(font)
        self.participantSelectButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resourcesnew/Group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.participantSelectButton.setIcon(icon5)
        self.participantSelectButton.setObjectName("participantSelectButton")
        self.horizontalLayout.addWidget(self.participantSelectButton)
        spacerItem2 = QtWidgets.QSpacerItem(18, 27, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.participantAddButton = QtWidgets.QPushButton(self.layoutWidget)
        self.participantAddButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.participantAddButton.sizePolicy().hasHeightForWidth())
        self.participantAddButton.setSizePolicy(sizePolicy)
        self.participantAddButton.setObjectName("participantAddButton")
        self.horizontalLayout.addWidget(self.participantAddButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.participantSelectedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.participantSelectedLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.participantSelectedLabel.setFont(font)
        self.participantSelectedLabel.setStyleSheet("QLabel {\n"
"    color: #B0B0B0;\n"
"    font: 6pt \"Microsoft JhengHei UI Light\";\n"
"}")
        self.participantSelectedLabel.setObjectName("participantSelectedLabel")
        self.verticalLayout_2.addWidget(self.participantSelectedLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.trialSelectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.trialSelectButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trialSelectButton.setFont(font)
        self.trialSelectButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resourcesnew/session.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trialSelectButton.setIcon(icon6)
        self.trialSelectButton.setObjectName("trialSelectButton")
        self.horizontalLayout_2.addWidget(self.trialSelectButton)
        spacerItem3 = QtWidgets.QSpacerItem(18, 27, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.trialAddButton = QtWidgets.QPushButton(self.layoutWidget)
        self.trialAddButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialAddButton.sizePolicy().hasHeightForWidth())
        self.trialAddButton.setSizePolicy(sizePolicy)
        self.trialAddButton.setObjectName("trialAddButton")
        self.horizontalLayout_2.addWidget(self.trialAddButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.trialSelectedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.trialSelectedLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trialSelectedLabel.setFont(font)
        self.trialSelectedLabel.setStyleSheet("QLabel {\n"
"    color: #B0B0B0;\n"
"    font: 6pt \"Microsoft JhengHei UI Light\";\n"
"}")
        self.trialSelectedLabel.setObjectName("trialSelectedLabel")
        self.verticalLayout_2.addWidget(self.trialSelectedLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.processButton = QtWidgets.QPushButton(self.layoutWidget)
        self.processButton.setEnabled(True)
        self.processButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: left;\n"
"    border-radius: 6px;\n"
"    background-color: transparent; /* Default background */\n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resourcesnew/processing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.processButton.setIcon(icon7)
        self.processButton.setObjectName("processButton")
        self.verticalLayout_2.addWidget(self.processButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exitButton.setMinimumSize(QtCore.QSize(164, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton {\n"
"   \n"
"    outline: none; /* Removes any focus border */\n"
"    font: 8pt \"Microsoft JhengHei UI\";\n"
"    text-align: center;\n"
"    background-color: #FFFCF8; \n"
"    color: black; /* Default text color */\n"
"    padding: 5px; /* Optional: Add padding for better spacing */\n"
"    border-radius: 6px; /* Rounded corners */\n"
"    border: 0.5px solid #c8c8c8; /* Light gray border */\n"
"    \n"
"\n"
"    /* Shadow effect */\n"
"    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAEAEA; /* Soft gray background on hover */\n"
"    color: black; /* Keep text black for readability */\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon8)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_3.addWidget(self.exitButton, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 30, 1051, 751))
        self.stackedWidget.setObjectName("stackedWidget")
        self.processPage = QtWidgets.QWidget()
        self.processPage.setObjectName("processPage")
        self.processLabel = QtWidgets.QLabel(self.processPage)
        self.processLabel.setGeometry(QtCore.QRect(490, 300, 131, 61))
        self.processLabel.setObjectName("processLabel")
        self.stackedWidget.addWidget(self.processPage)
        self.camerasPage = QtWidgets.QWidget()
        self.camerasPage.setObjectName("camerasPage")
        self.cameraSlot1 = QtWidgets.QLabel(self.camerasPage)
        self.cameraSlot1.setGeometry(QtCore.QRect(90, 10, 391, 291))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.cameraSlot1.setFont(font)
        self.cameraSlot1.setAutoFillBackground(False)
        self.cameraSlot1.setStyleSheet("border: 3px solid black\n"
"")
        self.cameraSlot1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraSlot1.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraSlot1.setObjectName("cameraSlot1")
        self.cameraSlot2 = QtWidgets.QLabel(self.camerasPage)
        self.cameraSlot2.setGeometry(QtCore.QRect(500, 10, 391, 291))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.cameraSlot2.setFont(font)
        self.cameraSlot2.setAutoFillBackground(False)
        self.cameraSlot2.setStyleSheet("border: 3px solid black\n"
"")
        self.cameraSlot2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraSlot2.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraSlot2.setObjectName("cameraSlot2")
        self.cameraSlot3 = QtWidgets.QLabel(self.camerasPage)
        self.cameraSlot3.setGeometry(QtCore.QRect(290, 320, 391, 291))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.cameraSlot3.setFont(font)
        self.cameraSlot3.setAutoFillBackground(False)
        self.cameraSlot3.setStyleSheet("border: 3px solid black\n"
"")
        self.cameraSlot3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraSlot3.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraSlot3.setObjectName("cameraSlot3")
        self.directoryLabel = QtWidgets.QLabel(self.camerasPage)
        self.directoryLabel.setGeometry(QtCore.QRect(470, 650, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.directoryLabel.setFont(font)
        self.directoryLabel.setObjectName("directoryLabel")
        self.camerasLabel = QtWidgets.QLabel(self.camerasPage)
        self.camerasLabel.setGeometry(QtCore.QRect(470, 670, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.camerasLabel.setFont(font)
        self.camerasLabel.setObjectName("camerasLabel")
        self.resolutionLabel_2 = QtWidgets.QLabel(self.camerasPage)
        self.resolutionLabel_2.setGeometry(QtCore.QRect(470, 690, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.resolutionLabel_2.setFont(font)
        self.resolutionLabel_2.setObjectName("resolutionLabel_2")
        self.framerateLabel = QtWidgets.QLabel(self.camerasPage)
        self.framerateLabel.setGeometry(QtCore.QRect(470, 710, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.framerateLabel.setFont(font)
        self.framerateLabel.setObjectName("framerateLabel")
        self.directoryValue = QtWidgets.QLabel(self.camerasPage)
        self.directoryValue.setGeometry(QtCore.QRect(550, 650, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.directoryValue.setFont(font)
        self.directoryValue.setText("")
        self.directoryValue.setObjectName("directoryValue")
        self.camerasValue = QtWidgets.QLabel(self.camerasPage)
        self.camerasValue.setGeometry(QtCore.QRect(550, 670, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.camerasValue.setFont(font)
        self.camerasValue.setText("")
        self.camerasValue.setObjectName("camerasValue")
        self.resolutionValue = QtWidgets.QLabel(self.camerasPage)
        self.resolutionValue.setGeometry(QtCore.QRect(550, 690, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.resolutionValue.setFont(font)
        self.resolutionValue.setText("")
        self.resolutionValue.setObjectName("resolutionValue")
        self.framerateValue = QtWidgets.QLabel(self.camerasPage)
        self.framerateValue.setGeometry(QtCore.QRect(550, 710, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.framerateValue.setFont(font)
        self.framerateValue.setText("")
        self.framerateValue.setObjectName("framerateValue")
        self.detectCamerasButton = QtWidgets.QPushButton(self.camerasPage)
        self.detectCamerasButton.setGeometry(QtCore.QRect(90, 630, 161, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.detectCamerasButton.setFont(font)
        self.detectCamerasButton.setStyleSheet("QPushButton {\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"    background-color: #231A16; /* Dark brown background */\n"
"    color: white; /* White text */\n"
"    font-size: 14px;\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Adjust padding for proper button size */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A2C26; /* Lighter brown on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #18120E; /* Even darker shade on press */\n"
"}\n"
"")
        self.detectCamerasButton.setIconSize(QtCore.QSize(20, 15))
        self.detectCamerasButton.setObjectName("detectCamerasButton")
        self.startRecordingButton = QtWidgets.QPushButton(self.camerasPage)
        self.startRecordingButton.setGeometry(QtCore.QRect(260, 630, 161, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startRecordingButton.setFont(font)
        self.startRecordingButton.setStyleSheet("QPushButton {\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"    background-color: #231A16; /* Dark brown background */\n"
"    color: white; /* White text */\n"
"    font-size: 14px;\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Adjust padding for proper button size */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A2C26; /* Lighter brown on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #18120E; /* Even darker shade on press */\n"
"}\n"
"")
        self.startRecordingButton.setObjectName("startRecordingButton")
        self.closeCamerasButton = QtWidgets.QPushButton(self.camerasPage)
        self.closeCamerasButton.setGeometry(QtCore.QRect(90, 690, 161, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.closeCamerasButton.setFont(font)
        self.closeCamerasButton.setStyleSheet("QPushButton {\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"    background-color: #231A16; /* Dark brown background */\n"
"    color: white; /* White text */\n"
"    font-size: 14px;\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Adjust padding for proper button size */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A2C26; /* Lighter brown on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #18120E; /* Even darker shade on press */\n"
"}\n"
"")
        self.closeCamerasButton.setIconSize(QtCore.QSize(20, 15))
        self.closeCamerasButton.setObjectName("closeCamerasButton")
        self.stopRecordingButton = QtWidgets.QPushButton(self.camerasPage)
        self.stopRecordingButton.setGeometry(QtCore.QRect(260, 690, 161, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopRecordingButton.setFont(font)
        self.stopRecordingButton.setStyleSheet("QPushButton {\n"
"    font: 8pt \"MS Reference Sans Serif\";\n"
"    background-color: #231A16; /* Dark brown background */\n"
"    color: white; /* White text */\n"
"    font-size: 14px;\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Adjust padding for proper button size */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A2C26; /* Lighter brown on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #18120E; /* Even darker shade on press */\n"
"}\n"
"")
        self.stopRecordingButton.setObjectName("stopRecordingButton")
        self.stackedWidget.addWidget(self.camerasPage)
        self.simulationPage = QtWidgets.QWidget()
        self.simulationPage.setObjectName("simulationPage")
        self.widget = QtWidgets.QWidget(self.simulationPage)
        self.widget.setGeometry(QtCore.QRect(10, 50, 500, 291))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(220, 140, 91, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.simulationPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1021, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.allTabButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.allTabButton.setStyleSheet(" font: 8pt \"Microsoft JhengHei UI\";")
        self.allTabButton.setObjectName("allTabButton")
        self.horizontalLayout_3.addWidget(self.allTabButton)
        self.hipTabButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.hipTabButton.setStyleSheet(" font: 8pt \"Microsoft JhengHei UI\";")
        self.hipTabButton.setObjectName("hipTabButton")
        self.horizontalLayout_3.addWidget(self.hipTabButton)
        self.kneeTabButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.kneeTabButton.setStyleSheet(" font: 8pt \"Microsoft JhengHei UI\";")
        self.kneeTabButton.setObjectName("kneeTabButton")
        self.horizontalLayout_3.addWidget(self.kneeTabButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setStyleSheet(" font: 8pt \"Microsoft JhengHei UI\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.jointsTable = QtWidgets.QTableWidget(self.simulationPage)
        self.jointsTable.setGeometry(QtCore.QRect(530, 50, 500, 291))
        self.jointsTable.setObjectName("jointsTable")
        self.jointsTable.setColumnCount(0)
        self.jointsTable.setRowCount(0)
        self.chartsWidget = QtWidgets.QWidget(self.simulationPage)
        self.chartsWidget.setGeometry(QtCore.QRect(10, 350, 1020, 251))
        self.chartsWidget.setObjectName("chartsWidget")
        self.label_2 = QtWidgets.QLabel(self.chartsWidget)
        self.label_2.setGeometry(QtCore.QRect(480, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.slider = QtWidgets.QSlider(self.simulationPage)
        self.slider.setGeometry(QtCore.QRect(10, 670, 1021, 22))
        self.slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 8px;\n"
"    background: #E0E0E0;  /* Light gray background */\n"
"    border-radius: 4px;   /* Rounded groove */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #8B4513;  /* Brown progress bar */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #E0E0E0;  /* Gray remaining bar */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: white;\n"
"    border: 2px solid #8B4513;  /* Brown border */\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 7px;   /* Circular handle */\n"
"    margin: -3px 0;       /* Center handle */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #8B4513;  /* Brown on hover */\n"
"    border: 2px solid #5C3317;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #5C3317;\n"
"    border: 2px solid #3D2309;\n"
"}\n"
"")
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.simulationPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 700, 1021, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rewindButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rewindButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resourcesnew/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon9)
        self.rewindButton.setObjectName("rewindButton")
        self.horizontalLayout_4.addWidget(self.rewindButton)
        self.backButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.backButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resourcesnew/Icon (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon10)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pauseButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/resourcesnew/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon11)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_4.addWidget(self.pauseButton)
        self.playButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.playButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/resourcesnew/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon12)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_4.addWidget(self.playButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.skipButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.skipButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/resourcesnew/Icon (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipButton.setIcon(icon13)
        self.skipButton.setObjectName("skipButton")
        self.horizontalLayout_4.addWidget(self.skipButton)
        self.fastForwardButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fastForwardButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/resourcesnew/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fastForwardButton.setIcon(icon14)
        self.fastForwardButton.setObjectName("fastForwardButton")
        self.horizontalLayout_4.addWidget(self.fastForwardButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.simulationPage)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 620, 1021, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.timeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_6.addWidget(self.timeLabel)
        self.timeValue = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.timeValue.setFont(font)
        self.timeValue.setStyleSheet("font: 25 8pt \"Microsoft YaHei UI Light\";")
        self.timeValue.setObjectName("timeValue")
        self.horizontalLayout_6.addWidget(self.timeValue)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gaitStageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.gaitStageLabel.setFont(font)
        self.gaitStageLabel.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.gaitStageLabel.setObjectName("gaitStageLabel")
        self.horizontalLayout_6.addWidget(self.gaitStageLabel)
        self.gaitStageValue = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.gaitStageValue.setFont(font)
        self.gaitStageValue.setStyleSheet("font: 25 8pt \"Microsoft YaHei UI Light\";")
        self.gaitStageValue.setObjectName("gaitStageValue")
        self.horizontalLayout_6.addWidget(self.gaitStageValue)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.frameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.frameLabel.setFont(font)
        self.frameLabel.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.frameLabel.setObjectName("frameLabel")
        self.horizontalLayout_6.addWidget(self.frameLabel)
        self.frameValue = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.frameValue.setFont(font)
        self.frameValue.setObjectName("frameValue")
        self.horizontalLayout_6.addWidget(self.frameValue)
        self.stackedWidget.addWidget(self.simulationPage)
        self.analyticsPage = QtWidgets.QWidget()
        self.analyticsPage.setObjectName("analyticsPage")
        self.tableWidget = QtWidgets.QTableWidget(self.analyticsPage)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.analyticsPage)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 270, 256, 192))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.analyticsPage)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 470, 256, 192))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.stackedWidget.addWidget(self.analyticsPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resourcesnew/Logo Text.png\"/></p></body></html>"))
        self.mainMenu.setText(_translate("MainWindow", "MAIN MENU"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.camerasButton.setText(_translate("MainWindow", "Cameras"))
        self.simulationButton.setText(_translate("MainWindow", "Analytics"))
        self.jointAnalyticsButton.setText(_translate("MainWindow", "Compare"))
        self.directoryMenu.setText(_translate("MainWindow", "DIRECTORY"))
        self.sessionSelectButton.setText(_translate("MainWindow", "Session"))
        self.sessionSelectedLabel.setText(_translate("MainWindow", "Session Name"))
        self.participantSelectButton.setText(_translate("MainWindow", "Participant"))
        self.participantAddButton.setText(_translate("MainWindow", "+"))
        self.participantSelectedLabel.setText(_translate("MainWindow", "Participant Name"))
        self.trialSelectButton.setText(_translate("MainWindow", "Trial"))
        self.trialAddButton.setText(_translate("MainWindow", "+"))
        self.trialSelectedLabel.setText(_translate("MainWindow", "Trial Name"))
        self.processButton.setText(_translate("MainWindow", "Process"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.processLabel.setText(_translate("MainWindow", "dashboard"))
        self.cameraSlot1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resourcesnew/Videocam Off.png\"/></p></body></html>"))
        self.cameraSlot2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resourcesnew/Videocam Off.png\"/></p></body></html>"))
        self.cameraSlot3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resourcesnew/Videocam Off.png\"/></p></body></html>"))
        self.directoryLabel.setText(_translate("MainWindow", "Directory"))
        self.camerasLabel.setText(_translate("MainWindow", "Cameras"))
        self.resolutionLabel_2.setText(_translate("MainWindow", "Resolution"))
        self.framerateLabel.setText(_translate("MainWindow", "Frame Rate"))
        self.detectCamerasButton.setText(_translate("MainWindow", "Detect Cameras"))
        self.startRecordingButton.setText(_translate("MainWindow", "Start Recording"))
        self.closeCamerasButton.setText(_translate("MainWindow", "Close Cameras"))
        self.stopRecordingButton.setText(_translate("MainWindow", "Stop Recording"))
        self.label.setText(_translate("MainWindow", "QtWebEngine"))
        self.allTabButton.setText(_translate("MainWindow", "All"))
        self.hipTabButton.setText(_translate("MainWindow", "Hip"))
        self.kneeTabButton.setText(_translate("MainWindow", "Knee"))
        self.pushButton_4.setText(_translate("MainWindow", "Ankle"))
        self.label_2.setText(_translate("MainWindow", "PyQtChart"))
        self.timeLabel.setText(_translate("MainWindow", "Time:"))
        self.timeValue.setText(_translate("MainWindow", "00:00:00"))
        self.gaitStageLabel.setText(_translate("MainWindow", "Gait Stage (°): "))
        self.gaitStageValue.setText(_translate("MainWindow", "TextLabel"))
        self.frameLabel.setText(_translate("MainWindow", "Frame:"))
        self.frameValue.setText(_translate("MainWindow", "1/n"))
import resources_final_rc
